### ISSUE TITLE
Правка HTML розмітки

### ISSUE THREAD

**Issue by dmytro-palyanytsya** [d-poddubny/mgk#2]

**Comment by Pavlovych** [comment]
оформити  input file

**Comment by Pavlovych** [comment]
Файл _gallery.html - розібратися з попапами - станні 5 шт вирівнюються в ліву сторону. Не розыбрався з :nth-child

**Comment by Pavlovych** [comment]
Главне меню - nav class="main_nav вирівнять текст ( в браузерах по разному )

**Comment by Pavlovych** [comment]
![fox](https://cloud.githubusercontent.com/assets/11021179/6318820/5edb7d4a-baad-11e4-8a3f-adbbef5b909a.png)
![chrome](https://cloud.githubusercontent.com/assets/11021179/6318821/5edd6b00-baad-11e4-96eb-3ca57d84db09.png)
![iaia](https://cloud.githubusercontent.com/assets/11021179/6318822/5edda340-baad-11e4-950f-c2b0e2315c04.png)
Відступи в між текстом різні і не по макету

**Comment by Pavlovych** [comment]
В футері проблеми тоже з шрифтом. Того розмір кегля зробив менше чим в макеті.
В хромі все прекрасно і дальше пєчалька

**Comment by ghost** [comment]
Блок 1: «ФОТОАРХИВ МГК»
С определенной периодичностью Фотографии из Фотоархива МГК меняются в блоке 1 Главной страницы сайта МГК.

**Comment by ghost** [comment]
gallery.html
Нажатием на соответствующую фамилию в Списке ушедших друзей МГК должна раскрываться
фотография с соответствующими надписями на фотографиях

**Comment by ghost** [comment]
photo_archives.html
Нажатием на соответствующее Сообщество МГК открывается Список событий, которые отражены в
фотографиях, размещенных в данном Сообществе.

**Comment by ghost** [comment]
Файл photo.html - скрипт для ролловера

**Comment by ghost** [comment]
photo.html - Скрипт не робе в Safari і Firefox
